force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Clients are the ones that hire the advisors services.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Legal Advisors are uniquely identified by its Account Number.</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ucl_UpsertManagerTest.cls
@isTest
private class Ucl_UpsertManagerTest {
  
    @isTest
    static void testUpsertLegalAdvisors() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('getJsonData');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        Test.setMock(HttpCalloutMock.class, mock);

        Map<String, Ucl_LegalAdvisor> legalAdvisorMap = Ucl_RestCallout.getData();

        Ucl_UpsertManager upsertManager = new Ucl_UpsertManager();
        Map<String, List<Ucl_Client>> clientsByLegalAdvisor = upsertManager.upsertLegalAdvisors(legalAdvisorMap);

        List<Legal_Advisor__c> legalAdvisorsUpserted = [SELECT Name, Account_Number__c, Account_Status__c FROM Legal_Advisor__c ORDER BY CreatedDate DESC LIMIT 1];
        Legal_Advisor__c legalAdvisor = legalAdvisorsUpserted[0];
        System.assertEquals('Riffpath', legalAdvisor.Name, 'Legal Advisor Name does not match');

        System.assertNotEquals(null, clientsByLegalAdvisor, 'Result should not be null');

    }

    @isTest
    static void testUpsertClients() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('getJsonData');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        Test.setMock(HttpCalloutMock.class, mock);

        Map<String, Ucl_LegalAdvisor> legalAdvisorMap = Ucl_RestCallout.getData();

        Ucl_UpsertManager upsertManager = new Ucl_UpsertManager();

        Map<String, List<Ucl_Client>> clientsByLegalAdvisor = upsertManager.upsertLegalAdvisors(legalAdvisorMap);

        upsertManager.upsertClients(clientsByLegalAdvisor);

        List<Client__c> clientsUpserted = [SELECT First_Name__c FROM Client__c ORDER BY First_Name__c LIMIT 1];
        Client__c client = clientsUpserted[0];
        System.assertEquals('Abbye', client.First_Name__c, 'Client First Name does not match');
    }



}