force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Clients are the ones that hire the advisors services.</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Key__c.field-meta.xml
<CustomField>
    <fullName>Client_Key__c</fullName>
    <description>This field is the concatenation of Legal_Advisor__c.Account_Number__c and Client.Client_Number__c</description>
    <externalId>true</externalId>
    <label>Client Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client__c/fields/Created_by_Admin__c.field-meta.xml
<CustomField>
    <fullName>Created_by_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the client record was created by an administrator. This checkbox helps identify records initiated by system administrators for reference and tracking purposes. Enabling this checkbox will prevent the record from being deleted by the nightly service.</inlineHelpText>
    <label>Created by Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ucl_ClientDelete.cls
public with sharing class Ucl_ClientDelete {
  public void clientDelete(Map<String, Ucl_LegalAdvisor> fetchedData) {
    List<String> incomingClients = new List<String>();

    for (Ucl_LegalAdvisor legalAdvisor : fetchedData.values()) {
      if (legalAdvisor.accountStatus == 'Enabled') {
        for (Ucl_Client client : legalAdvisor.clients) {
            incomingClients.add(legalAdvisor.accountNumber + client.clientNumber);
        }
      }
    }

    List<Client__c> clientsToDelete = [SELECT Id FROM Client__c WHERE Client_Key__c NOT IN :incomingClients
     AND Created_by_Admin__c = false];

    if (!clientsToDelete.isEmpty()) {
      try {
        delete clientsToDelete;
      } catch (DmlException e) {
        Ucl_ErrorLogManager errorLogManager = new Ucl_ErrorLogManager();
        errorLogManager.logError('Exception', 'Exception: ' + e.getMessage(), 'Ucl_ClientDelete > clientDelete()');

        Ucl_EmailNotificationManager.sendErrorEmail(
          'Exception: in clientDelete',
          'Exception: ' + e.getMessage()
        );
        
      }
    }
  }
}