force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Legal Advisors are uniquely identified by its Account Number.</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ucl_UpdateLegalAdvisorStatusTest.cls
@isTest
private class Ucl_UpdateLegalAdvisorStatusTest {

    @isTest
    static void testUpdateLegalAdvisorStatus() {

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('getJsonData');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        Test.setMock(HttpCalloutMock.class, mock);

        Map<String, Ucl_LegalAdvisor> legalAdvisorMap = Ucl_RestCallout.getData();

        Legal_Advisor__c testLegalAdvisor = new Legal_Advisor__c(
            Account_Number__c = 'd0145909-0028-47a4-8f85-8f8b50e7c08e',
            Account_Status__c = 'Enabled',
            As_of_Date__c = Date.valueOf('2019-6-9')
        );
        insert testLegalAdvisor;

        Ucl_UpdateLegalAdvisorStatus updateManager = new Ucl_UpdateLegalAdvisorStatus();
        updateManager.updateLegalAdvisorStatus(legalAdvisorMap);

        Legal_Advisor__c updatedLegalAdvisor = [SELECT Id, Account_Status__c FROM Legal_Advisor__c WHERE Account_Number__c = 'd0145909-0028-47a4-8f85-8f8b50e7c08e'];
        System.assertEquals('Disabled', updatedLegalAdvisor.Account_Status__c, 'Legal Advisor Account Status should be Disabled');
    }
}