force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Legal Advisors are firms that provide legal services to different clients</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Legal Advisors are uniquely identified by its Account Number.</description>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ucl_UpdateLegalAdvisorStatus.cls
public with sharing class Ucl_UpdateLegalAdvisorStatus {
  public void updateLegalAdvisorStatus(Map<String, Ucl_LegalAdvisor> fetchedData) {
    List<String> disabledAccountNumbers = new List<String>();
    List<Legal_Advisor__c> legalAdvisorsToUpdate = new List<Legal_Advisor__c>();

    for (Ucl_LegalAdvisor advisor : fetchedData.values()) {
      if (advisor.accountStatus == 'Disabled') {
        disabledAccountNumbers.add(advisor.accountNumber);
      }
    }

    if (!disabledAccountNumbers.isEmpty()) {
      String soslFindClause = '{' + String.join(disabledAccountNumbers, ' OR ') + '}';
      List<Legal_Advisor__c> searchList = [
        SELECT Id, Account_Number__c, Account_Status__c
        FROM Legal_Advisor__c
        WHERE Account_Number__c IN :disabledAccountNumbers
          AND Account_Status__c = 'Enabled'
      ];

      for (Legal_Advisor__c legalAdvisor : searchList) {
        legalAdvisor.Account_Status__c = 'Disabled';
        legalAdvisorsToUpdate.add(legalAdvisor);
      }

      if (!legalAdvisorsToUpdate.isEmpty()) {
        try {
          update legalAdvisorsToUpdate;
        } catch (DmlException e) {
          Ucl_ErrorLogManager errorLogManager = new Ucl_ErrorLogManager();
          errorLogManager.logError('Exception', 'Exception: ' + e.getMessage(), 'Ucl_UpdateLegalAdvisorStatus > updateLegalAdvisorStatus()');

          Ucl_EmailNotificationManager.sendErrorEmail(
            'Exception: in updateLegalAdvisorStatus',
            'Exception: ' + e.getMessage()
          );
        }
      }
    }
  }
}